apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: m-react-app
  template:
    metadata:
      labels:
        app: m-react-app
    spec:
      containers:
      - name: m-react-app
        image: yash5090/m-react-app:latest
        ports:
        - containerPort: 3000
